name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Needed to push to output branch

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation Generation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mahu0926
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to output branch
      - name: Push to GitHub Pages output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

